config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'sessions#new'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "dashboard" => "welcome#index", :as => "dashboard"
  get "gallery" => "card_galleries#index", :as => "gallery"

  resources :users
  resources :sessions

end

app/models/mtg_card.rb
class MtgCard < ActiveRecord::Base
  require 'mtg_helpers'
  include MtgHelpers

  has_many :mtg_card_types
  has_many :mtg_types, :through => :mtg_card_types
  belongs_to :mtg_set

  validates :name, :presence => true
  validates :mtg_set_id,  :presence => true

  alias_method :types, :mtg_types
  alias_method :set, :mtg_set

  def transformed_side
    if transformed_id.present?
      MtgCard.find_by_multiverse_id(transformed_id)
    end
  end

  def image_url
    prefix = using_asset_pipeline? ? asset_pipeline_prefix : "/images"
    "#{prefix}/#{set.folder_name}/#{multiverse_id}.jpg"
  end

  def set_symbol_url
    prefix = using_asset_pipeline? ? asset_pipeline_prefix : "/images"
    "#{prefix}/#{set.folder_name}/#{slugify(rarity)}_icon.jpg"
  end

end

app/models/mtg_card_type.rb
class MtgCardType < ActiveRecord::Base
  belongs_to :mtg_type
  belongs_to :mtg_card
end

app/models/mtg_set.rb
class MtgSet < ActiveRecord::Base
  require 'mtg_helpers'
  include MtgHelpers

  has_many :mtg_cards
  validates :name, :uniqueness => true, :presence => true

  alias_method :cards, :mtg_cards

  def folder_name
    slugify(name)
  end

  def common_icon
    prefix = using_asset_pipeline? ? asset_pipeline_prefix : "/images"
    "#{prefix}/#{folder_name}/common_icon.jpg"
  end

  def uncommon_icon
    "#{prefix}/#{folder_name}/uncommon_icon.jpg"
  end

  def rare_icon
    "#{prefix}/#{folder_name}/rare_icon.jpg"
  end

  def mythic_icon
    "#{prefix}/#{folder_name}/mythic-rare_icon.jpg"
  end

  def special_icon
    "#{prefix}/#{folder_name}/special_icon.jpg"
  end

  def promo_icon
    "#{prefix}/#{folder_name}/promo_icon.jpg"
  end

  def land_icon
    "#{prefix}/#{folder_name}/basic-land_icon.jpg"
  end

end

app/models/mtg_type.rb
class MtgType < ActiveRecord::Base
  has_many :mtg_card_types
  has_many :mtg_cards, :through => :mtg_card_types
  validates :name, :presence => true, :uniqueness => true

  alias_method :cards, :mtg_cards
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_authenticated
  redirect_to login_url, :alert => "First login to access this page."
  end
  
end

app/controllers/card_galleries_controller.rb
class CardGalleriesController < ApplicationController

	layout 'darkMagic'

  def index

	@sets = MtgSet.find([1, 2, 3, 22, 34])
	


  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	layout 'login'
  def new
  end

	def create
	  user = login(params[:email], params[:password], params[:remember_me])
	  if user
	    redirect_back_or_to dashboard_url, :notice => "Logged in!"
	  else
	    flash.now.alert = "Email or password was invalid"
	    render :new
	  end
	end

	def destroy
	  logout
	  redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	layout 'login'
	
	def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

	def new
	  @user = User.new
	end

	def create
	  @user = User.new(user_params)
	  if @user.save
	    redirect_to root_url, :notice => "Signed up!"
	  else
	    render :new
	  end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	layout 'darkMagic'

	def index

		@sets = MtgSet.all

		set = MtgSet.find_by_name('Worldwake')
		@setName = set.name
		@cardsInSet = set.cards

	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_galleries_helper.rb
module CardGalleriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/card_galleries/index.html.haml
%center
  %h2 CARD GALLERY
- @sets.each do |set|
  %div
    %h3= set.name
  %table.table.table-striped.posts
    %thead
      %tr
        %th.span2 Name
        %th.span4 Oracle Text
        %th.span1 Rarity
        %th.span2 Type
        %th.span3 Mana Cost
        %th.span1 Converted Mana Cost

    - @cards_in_set = set.cards.includes(:mtg_types)
    - @cards_in_set.each do |card|

      %tbody.page
        %tr
          %td.span1
            %a.screenshot{href: card.gatherer_url, rel: card.gatherer_image_url}
              = card.name
          %td.span5= card.oracle_text
          %td.span2= card.rarity
          %td.span2= card.mtg_types.collect{|type|type.name}
          %td.span1= card.mana_cost
          %td.span3= card.converted_cost

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Myapp
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/darkMagic.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Tolarian Academy"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar
      .navbar-inner
        %ul.nav.pull-right
          %li
            %a.hidden-phone.visible-tablet.visible-desktop{href: "#", role: "button"} Settings
          %li#fat-menu.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#", role: "button"}
              %i.icon-user
              - if current_user
                = current_user.email
              %i.icon-caret-down
            %ul.dropdown-menu
              %li
                %a{href: "#", tabindex: "-1"} My Account
              %li.divider
              %li
                %a.visible-phone{href: "#", tabindex: "-1"} Settings
              %li.divider.visible-phone
              %li
                - if current_user
                  = link_to "Log out", logout_path
        %a.brand{href: "index.html"}
          %span.first Tolarian Academy Database

          
    .sidebar-nav
      %form.search.form-inline
        %input{placeholder: "Card Search...", type: "text"}/
      %a.nav-header{href: "help.html"}
        %i.icon-align-justify>
        Decks
      %a.nav-header{href: "help.html"}
        %i.icon-tasks>
        Draft Simulator
      = link_to "  Card Gallery", gallery_path, class: "nav-header icon-picture"
      %a.nav-header{href: "help.html"}
        %i.icon-fire>
        Planswalker Points
      %a.nav-header{"data-toggle" => "collapse", href: "#accounts-menu"}
        %i.icon-briefcase>
        Account
      %ul#accounts-menu.nav.nav-list.collapse
        = menu_item('Sign In')
        = link_to "Log out", logout_path
        = menu_item('Reset Password')
      %a.nav-header{href: "help.html"}
        %i.icon-question-sign>
        Help
    .content
      .header
        %h1.page-title
          - if current_user
            = current_user.email
          Dashboard
      .container-fluid
        .row-fluid
          = yield


    %script{src: "lib/bootstrap/js/bootstrap.js"}
    :javascript
      $("[rel=tooltip]").tooltip();
      $(function() {
          $('.demo-cancel-click').click(function(){return false;});
      });

app/views/layouts/login.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Tolarian Academy"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
      
  %body
    .navbar
      .navbar-inner
        %ul.nav.pull-right
        %a.brand{href: "index.html"}
          %span.first Tolarian Academy Database
    %div
      = yield

app/views/shared/_posts.html.haml
- posts.each do |post|
  .post
    = post.title

app/views/users/new.html.haml
.row-fluid
  .dialog
    .block
      %p.block-heading Sign Up
      .block-body
        = form_for @user do |f|
          - if @user.errors.any?
            .error_messages
              %h2 Form is invalid
              %ul
                - for message in @user.errors.full_messages
                  %li= message
          .field
            = f.label :email
            = f.text_field :email, class: 'span12', placeholder: "Username"
          .field
            = f.label :password
            = f.password_field :password, class: 'span12', placeholder: "Password"
          .field
            = f.label :password_confirmation
            = f.password_field :password_confirmation, class: 'span12', placeholder: "Password"
          %label.remember-me
            %input{type: "checkbox"}/
            I agree with the
            %a{href: "terms-and-conditions.html"} Terms and Conditions
          %br/
          .clearfix
          .actions= f.submit
          %br/
          %center
            %div
              Already have an account? #{link_to 'Log In', login_path}
    %center
      %p
        %a{href: "privacy-policy.html"} Privacy Policy

app/views/welcome/index.html.haml
%h3 Welcome to your Dashboard!